# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 19 Nov 2020 01:45:18 +0000
*               @ALL          1
*               @user         8
