<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: pisaucer
 * Date: Wed, 18 Nov 2020 23:29:59 -0500
 */

$conf['title'] = 'Unofficial New Caledonia';
$conf['license'] = '0';
$conf['dformat'] = '%m/%d/%Y %H:%M';
$conf['showuseras'] = 'username';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin,PiSaucer';
$conf['plugin']['captcha']['loginprotect'] = 1;
