# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 19 Nov 2020 01:45:18 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated
# if locked out use "$1$4fd0ad31$.cId7p1uxI4a.RcrH81On0" its hash is "admin"

