name: Generate xml sitemap
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         fetch-depth: 0 
      
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://newcaledonia.us/
          # include-html: false
          
      - name: Get Hash
        id: hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Sigin and push to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Sitemap - ${{ steps.hash.outputs.sha_short }}"
          git push
