name: Generate xml sitemap
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
     
      - name: Get Hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
     
      - name: Sigin to git and remove old sitemap
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rm sitemap.xml
          git commit -m "Remove Sitemap - ${{ env.hash }}"
      
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://newcaledoniadevteam.github.io/NewCalWebsite/
          include-html: false
          
      - name: Sigin to git
        run: |
          git add sitemap.xml
          git commit -m "Update Sitemap - ${{ env.hash }}"
          git push
